select = [
  "E", "F", "W", # flake8
  "I",           # isort
  "B",           # flake8-bugbear
  "RUF",         # Ruff-specific
  "UP",          # pyupgrade
  "NPY",         # Numpy specific 
]
extend-ignore = [
  "E501",   # Line too long
  "W293",   # whitespace on blank line  black will handle
  "W291",   # trainling whitespace black will
]
target-version = "py39"
src = ["py4DSTEM"]
unfixable = [
  "F841", # Removes unused variables
]
exclude = ["*__init__.py"]