name: blacktest
on:
  repository_dispatch:
    types: [test-command]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: psf/black@stable